### ISSUE TITLE
Embed Disqus

### ISSUE THREAD

**Issue by kfrie** [kfrie/SAFE-Documentation#2]
Should we embed [Disqus ](https://disqus.com/) for the released documentation. Could be configured with mkdocs in no time.

This would be more inviting towards feedback. I think with our developer audience this could provide good insights. Any comments on that?

**Comment by MangelMaxime** [comment]
If we want feedback we probably should linked to an issue because it's easier to track. Last time I checked Disqus was only about commenting an article not sure of the benefit for feedback. Could easily get messy no ?

**Comment by kfrie** [comment]
For every .md file there is an edit link in built documentation that opens it in GitHub editor. This invites to contribution and PRs 

I thought that Disqus could be use additionally. For instance if a beginner has a question he will most likely not send a PR. So that would be an additional source for insights. But in practice, this could also be bad I don't know yet. 

Maybe open it for a trial period and shut it off when we know most of problems and documentation is in a really stable state?

**Comment by kfrie** [comment]
I thought that Disqus could be use additionally to issues. For instance if a beginner has a question he will most likely not open an issue. So that would be an additional source for insights. But in practice, this could also be bad I don't know yet.

Maybe open it for a trial period and shut it off when we know most of problems and documentation is in a really stable state?

But I will look for a way to integrate opening an issue by link from documentation, that's a good idea
