### ISSUE TITLE
How can Saturn and SAFE complement each other?

### ISSUE THREAD

**Issue by kfrie** [kfrie/SAFE-Documentation#6]
I had a quick look into [Saturn](https://github.com/SaturnFramework/Saturn) from @Krzysztof-Cieslak and wondered how that fits in with the SAFE stack. 

I have to say I like some of the concepts but I think this can even generate more fragmentation with the whole "F# and the Web" story.

Any ideas how those 2 projects could complement each other?

**Comment by alfonsogarciacaro** [comment]
There's already a PR to use Saturn with SAFE: https://github.com/SAFE-Stack/SAFE-BookStore/pull/286

**Comment by Krzysztof-Cieslak** [comment]
Yes, in terms of SAFE stack, Saturn fits in exactly same place as Suave and Giraffe, just provides a bit higher level of abstractions and more framework-ish feel. It's perfectly fine for creating APIs that powers Fable/Elmish apps so no problem here at all. I'm actually planning to work on some deeper integrations between Saturn and Fable/Elmish.
